### PR TITLE
fixing error in view.pt

### PR DESCRIPTION
**Pull request by kakshay21**
fixing  building error in Travis CI
@hvelarde

### CODE REVIEW

**Comment by hvelarde** [comment]
@kakshay21 we're experiencing RF issues all over the place; we're trying to figure out what's going on.

**Comment by kakshay21** [comment]
Can I help in any way?
@hvelarde

**Comment by hvelarde** [comment]
no, thanks! we still have no idea what's going on.

please add a line to the changelog describing your fix.

**Comment by kakshay21** [comment]
changed the 18th line where the spelling of absolute was "absolut"
in view.pt
@hvelarde

**Comment by kakshay21** [comment]
What's the status? @hvelarde

**Comment by hvelarde** [comment]
I'm currently testing with a new release; check this commit to understand what I mean when I say you're missing a changelog entry: https://github.com/collective/collective.behavior.amp/commit/b84c4d460f9eacbd093c10fa09220db44399244a

**Comment by hvelarde** [comment]
tests are passing again, but you should update your fork.

**Pull request closed without merging**
